// Package imagebuilder provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package imagebuilder

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9b3PcNpL3V0Fxn6rYW/PHdpLn7lR1VafIdlZnO/ZK8u6LtSuFIXtmsCIBGgAlT1zz",
	"3a+6AZLgDDhD2ZJiJ/Mq1gBsNLob3b/uBplPSaqKUkmQ1iRHnxKTLqHg9M+fhMyEXFysSsA/MzCpFqUV",
	"SiZHycUSmF2VwNSczdxENlea2SUwUfAFsFkl8mySjBKQVZEc/SsBrvNVMkpybiF5P0osEU6M1UIuklHy",
	"cYwzx1dcS16AwUcCFp75p4OfXhKh9SihMT+wzSqNNkymSs7FotIcR9mYQTGDzLAUtBVzkXILTMh2G7iB",
	"UqsSh4HEYofKY3vvW5ter0eJhg+V0JDhNBptZ6nZvyG1Ce7wY6m0fa50we1+hcxpHrOKAT0XaMWqkK2r",
	"IrtMRsmHVF0/SUaJMKr+a5wJczlOlbRcSNAD9bXJ5j9ePX2RbHP/95PX/3wS+f30/HXf7KfCXJ603KxH",
	"ySnu5yc0sm1htGNMQ6nBoHkz7mySocTBWLJXzpo99imcl+IfoA1R3lzo+M2pH2MZzIUEQ7K+cr9Bxtx5",
	"QqXYpTAtN8781JxxyZyaJ+wcND7IzFJVeYaMXYG2TEOqFlL81lAzqFlcBk+SsUxIC1rynF3xvIIR4zJj",
	"BV8xDUiXVTKgQFPMhL1SGg19ro7Y0trSHE2nC2Enl/9pJkJNU1UUlRR2NUXpaDGrrNJmmsEV5FMjFmOu",
	"06WwkNpKw5SXYkzMStyUmRTZXzQYVekUDIpzw+ZHCQnamaaJyFRrvkLRkBadNbCGILNLjn/OQYNMwYm1",
	"1feEvZb5ipWqrFA6GbtegmTXwi4dIcM+VKBXrOSaF2BR64ZZXZHehYWCGPp/GubJUfKXaescp17204Ar",
	"3IvfHEem8e9LISMG+ULIDFfizEnB6aE1B/wJNXr27Pyi2avbm7OOwI5bQ0ElCzkH7WbOtSqICsisVEK6",
	"c5/mAqRlppoVwpra+NGGJuyES6ksmwGrygzFNWGnkp3wAvITbuDOzQSFZ8YosrihFGB5xi3fp5NUafj1",
	"6vEMLH/8qypB8lL8+poE9wosR1KmhHSQasmMznE2PmW5rcwNnnPzN/164EK8hQR787zF3H5LuDe6bU1h",
	"SE3MBZiemFeH6SZAZwIJFkJyqzSuUPCy9Iu5wNWz707c9YG9ZyrG6nrmuvGwq194gY/QxtejREl4PU+O",
	"/rVb3J1l16PdkzsLd+PGiZKZsN6v8zwfsHTU0Bo6P3EDxFAcMQwzoYYaxfmBCOH9aMMsGiqk7k48bDxz",
	"XBhnwE0s1LnfG+sJSJ4Bz1ZoZI5ACDDeQG0cNNX9801llu5fJ6ooc7CA5+E5Fzn944TLFHI/gf4N2UD8",
	"0budlo/eKQGD/WQaznunhFvqndTstZ9MIIQ9k1A6cVX2IEWPEgMNRnVHav18weMynkSHu6dgLLqaKJ6K",
	"Tgs8GlpeFoyEvsz2ATj62XmaGGrGTTiABkxVtqwCQnHocsEXPQCcLwZT0lAqI6zSq/1snTVzW3CAQ6jJ",
	"1yeniAfLyiw3ReHR/u6cI+BjFIgq2OruyPRSGLtLkTjuoE+O/+oaXgcnHmD3HcPuGt52hflyj1qGo2KX",
	"jR1A8VcMilHZDhLfDKI6I9jtCc5gfk462uUOmkmBV+fM69Z5LVIZlzGD7HHuNeX9njRCE491ZYBxw9pF",
	"tqS+v+zTPlxH0Ja3gaWf0cZ2dst7v7C3JI0i6Mp6Mxn47NAZkv2y0LmX0m2GTl/+qX3NnrVvOXae+6S0",
	"V38lpMwNzmrtOV2mLf7hcrPi2tXhrE0dh3nwIE/LumBt2PMhwsMcujHTgTm0m78eJZUBfRLmrsOJvN16",
	"dFN3nq3uHkeNtPYorqkL9KqOZoTlR4o7ldYUeNyoAyJB9WobBQXBIm7s4Yza6Dfg8NYBavB+ZAsnnsV2",
	"zrbv/AxY0CbbEXxAnJ7VNb34PudVnntDb6t/2/tlD2CymIzYh4qvMBwrvZjSADqFI8sXD6MSybmx5wAy",
	"vjaOMisKaH0lu8Z4ASDZgyVwbWfALZF2xffkKEHsMMaHokGcSzEHY5+KBcTwM66a0Vhsj/XTcQ+1w27f",
	"xk5UnwlvTQ4CCR7NfXWlriWX1SwX6SX0+Gw3zC5h1RDaXiOqOpwme0NUPXozqhu+olliFGyj10P44nBc",
	"sk09u21LyLpNUzcmrGqyEEwqKLUjxVMKkok5mb/1fZ5D7nQPudMhg/nGy/ru3H1GXd8/eAeFfUf5q6tC",
	"b7B122XozYbepE8eNylEe6KDKtEnzkndSy06uqWNYnR0TofJHaS6BekeUhsV6eisbkk6TmizJr1jVliU",
	"jhnU7qq0V+ftlKUjy2/UpcMbB2+WeHziEAWHKAAyI+Qih/qihQt7ZoPRDxVUJNE01GXZaCz1ekHM6IR/",
	"400FLP+9Xi0+3GdPwZSoLXVINPzGJ3gT2hDrjvpwOyFSIN72EweU8zVUiGN6OVycONSI99aIPZDaVbQM",
	"pwypWrq8ad8dhqAMu7dM0dawv/SWQpTm+5gwLgaWljcuWLabH1Jv3hdKWlaCVs4mu/3lynbC8Hplu4Gu",
	"X68rKHtugWxeibxZqbFjjb21Qc/KPpveVQ0MpwwvBz7rkc0XVO5akjd11ztrdzepnPk6x32XztyykG1U",
	"z/x5wgBACw+spoU3irZDJbfQe9c4gyuRumHDuGVzoY1lM6XsLV0zjl+tHnzL+MzHzxfRUHzWRFcMPiRU",
	"g8BF8I3qMGh2/OY05CtwKd0a2fuIfvtOkz9CBAY02EpLDwZQjSnPc383NFPyO1vPUHYJ2kOBA4S8BwiZ",
	"qixit+fVAg8kZOxvFxdvauXg3PYQOic4Yo+YmDNEVwZsxysIab9/0q6JolmAPmDHW8eOxvBFRInHbFkV",
	"XI418IzPcmDBcNO7bSKZk2MJOyr3uqfCc8wKni6FhN6lrperjQVQ0f7FjXdUv6k0vEs8PxN26hlyJiAM",
	"g6K0SAM0/SkVSRwtDYnxKy5yXHjCjpkvOKU51/6+gnRm7DdLZjyr0POAIctVV6C1yIAJG9242e3i6itk",
	"jfDYa4ku/4i9S86rNAVj3iVM6XCnd242COTGXGZjL9K9TZNYtuA37t1EYwGt0cXC0oBy55Yk8dcWCKED",
	"qFyHdK7yXF3j0X9RzUBLsGAwXLFwu+ytAXppgFFBFn0yzzJ0JB7NuiCM4W07piDkudBcGlduEn2dqS40",
	"anm1zbOQOfeiZHOwkBNJQe0GgKnvQP8NjzNrzpifxxBXIF6XC5aB5SI3jM9UZT3HDXtR01Yzg44y+xkk",
	"9LUYcfeTOnGcLJqZLn53peGwomUzjmCjKt2yYUz4/z9EY0K/c3kw0wLmD5nuFpKbNb8zg3Y6rIew23h7",
	"2grNMYnY0q0cmvNBDqiRyIhMUM3ZhUYQ8pznBkbsrbyU6rpT88Rxqp/nBv/rZwzMRje487Q2fq1Jb/zc",
	"rNS39aaoEa1u4UiQuNa26QzSrKRdghVp8BZSURnLlvwKRkzINK8I7+fCUD8XoZgWqjJNOPT4kx23OANx",
	"BBJgSuarWr6f2u7WiNWMraNpoBWyipzpV3yF0AKPjJi3DW/8m7NcFMIy5cKkrIoZYuM5o3zQgzLIHMj0",
	"TqB+4YpiOyEgtuSGFRhrSEJBpMRj3cRXVfIPFTR4dUZ8ZOi/hDE04KB50PPeQFEoeXIlLnJTcdgqZFML",
	"uHJeU8JHwomEtmtOWnGfODGhbuhFPyOMRVxGtJAtD8RKZYzAJ73I/E67+RvuO11yuYAMYy+JwC65ZJzN",
	"4ZoVQlYoLtJpyY1BYIciqTVeJxNzAXT70EnbvaBWGQdGhWG1ar0or0WeI4siw+CU8ryWlJe006XLJDWY",
	"Ukk8mpXMwRi2UpXjR0MKohGlVZcgm2uWoDVux/mSHpxWuCtypxaKE1XJnqy7tShTzQwqVlpvXJ5PEvz1",
	"UqRLxjWQ+N3xweRcBoqut+KRG9S/OmOp39nMWM5nkKM6nFQN5JAisBnhQ5t23uyjZsqwyvkNslMnSCRT",
	"Cz2HOeZYdHhkxlQhLOYwWUXphAEteC5+8xgtZJT06Nol7AEIsvQZpLwyiAkd4LQsXVbyEimpdpREIIzP",
	"AY2f9LDdjwYvOmeBm3tyG8HE5PN3Uqc6inJ5svGrx5PHP7JM1YlZsIazcoy8EtVYmeZa1rbd4M7+CsaK",
	"gvDFX91pE7/5tlqqctQfMXFCKVSTMeO6GshT9tG2qvZ8GNHpD/jIUzsIMKyHxtDg/sHWIWjHcKPdKMLz",
	"nJXoAigNjkYSdzD8gTD0hHdl5MT93FQDt7H3lDGt5E1tkGcuPvL8TaSwFJzu7hbayQ52rRqHKDo3owMp",
	"IT8enRjLi7KnbFUjXZ9bI7BzW8mGQ9kMcvictfwpoMdvst5iB4o9Zs7FpY2L6VQWgmQhQLj+ZGRgEOsR",
	"PoAJe9O8rlzLe2UsFBO60DBGgDAQ9JI7/BL1v+Il+W9XMLmEVY1n8qqGAimXYThXesElnmCch4hhoTT+",
	"+cCkqnS/Oq/8MCzDbVmRHPZ+liunRROPawk6pqWgssMtU9fS1PU69zsiOPaOMtQprvUu6a8HYyzsRPPI",
	"grLGPl6ItKwL3203izzsdyao73l00CkbDilIYyYCaaWFXZ1jzuEvfQPXoI8ru+xNULoPxROVgEyfP+yu",
	"5P56Xlvq//7zArN+WiI58qPtrpbWlr2ElV6cZnGTePv29GljEs7+ggTSq7hFXhPGXvHSJ8+dB1onPUHV",
	"U3MEF6GPBCS1VSZKL34VWcs3L8ULoO5Hw+Rni9hRWKMehZyrGt3zlEAWRrk8OUos8OJ/5rlYLG1q84lQ",
	"LXMokOc0QnhXq5xdAC+SUVLp3AvZHE2nnae3Dj5V5Vldv/f+nnLjLu3JO3lB1Vo/o+CSLqYGryAEwQ2f",
	"n/kXa5u7rL41En51w0zeYUKbixSkK+f4zR2XPF0CezJ5tLWf6+vrCafhidKLqX/WTF+enjz75fzZ+Mnk",
	"0WRpi5yaVsLmSG5DTt1NH785TUbJVX2wk6vHPC+X/DHp2WkrOUq+nzyaPMbgy+2SjtqUl2J69djdMqfN",
	"0s8LsD03KfpetGvqfWhRNLWdaWhF/80KQ83n7WjksK9LktBhpLZFpAR/fcpRgwoXbIR2KNr0WT+Nnnvq",
	"9XHmkWCyHt0qV4Que7mi0c/jCk9MwT+Koio62YGpctvmwZ2cpclH+mSEmXWHi71ti4i0MHS4oB18oMQq",
	"/80Sj/cdl03fwYWSPr6aQsGNBISpDFV6GiyqweGT+DdZhGTA02Vo2aKG6bvlFnyZpcNiBnNe5TY5mlOt",
	"qWZ5plQOXCbr9XsKxUSbjtuTR49q1wkuP+Vlmft7B9N/+1Jgu8Cwqxt0eY188wbQf4FO4YdbXLOpBG6t",
	"9RPP2JlLfN2ij+9h0beSV3ZJSC5zq35/D6s+V3omsgzoosEPT/7rHpa8UIq94nJVi9jg0j/ey27PfQh9",
	"K5vSlQN4fGGa6zyz5iJOqWK3HU4ohdrxumw3qrjpnX68L6r8pLLVHZwgt/G2uI1+Zb11dh/f2coxaWWH",
	"w3vnh/fRfRzeEyXnuXAJ5MFddN3Fx3HtBRB0BNh0PYpB1uknjMhr52DomveWq3lKvw92NW56x9XsRLAD",
	"XtVvUASC7xZE+Ffzuk5mF+C5H/CwCzj8adzAD/ew5C/KsueqktnBD2z7gWge+jP1AYad45/BfpWH+Day",
	"lj9AinLwMgcv862ijWlKLwvS5wHi2Q2NM850JanJufWlV0cPz7J/rXLE6i/5jZjSzL/V5jotde8i9e8o",
	"RvIjGrlVf0ev8xPZPw58OaROfyxvdq/ZGhu7I+qvf/jDQTd36JQe/Otw/1p70N1uNleL3pYEQsFcLUz9",
	"blYMsbHnOJZaceVbPGbEjNXAC+OezcWVn1Vfe8maia6e7u9U/vjoEcuFjDU8OjjzpVp8E1DTScEJwdfa",
	"VWXyFXuQi0tgl9UMUpu78fH8YVSSlwAlPS3d3RemSpD7pMlzT5Xa7rky0N8poSvPt41dLXy0U7gCacdO",
	"CN1TsdH3Uov6i6jc+PtF43OQlj27crd8nBwf0G04x/B/o4SdVYbyehhviiM3Zc6FHM4GTWf4ZHddkgnd",
	"KYtoILb8AX8f8PfXGh/Q9W8Gh+B/vbCnSx172b+nTd2myIc+9aFPfSd96jvPe4IvlhySn0PT93fz6+Df",
	"jh7a9d1w0zvbvv7N6zvs+9bfePkdGr/h0ofO76Hz++f0GdtgsEZ8PUjw5s3fvR4n6P42Hufm6XxkmW+i",
	"gNrvhw6p4SE1vGd3sLcDvPcw16W5w0k+nOTDSf72Avtn9ln9F8Nco9VT7HRa26+KfmGv9fYcyzfYbd3v",
	"Yg75yqHd+iXtVn9GDv3WW3C1fR3XDY+bqWuZK571Ftmf+gmbKIxrK+Y8tW3lVMNCGKtXkSTL0/hDgDOV",
	"Woj3EpsS9UxITlXjAR04NmbHtShnuZqxetn1KPn+0ZNthdDxZGN2BpnQkPqPjTjROwpvz14mo2QJPCPZ",
	"fkpeqrR5ObxfDGta8T8ir7JCUSrN9apd846WP4SQAzS+PX99H7Z0Wr8Y7y4LsGdaK/0thosmEOwJGDe+",
	"o7PptMOrJZ72gFs6zcybXtPxvbLPvKdzRxHnbi7qNDIadFNnS6J/wqs6Xga/212dHesf6jiHOs7XGy3o",
	"ug590oU+wUXu1H32Ykr/eyVPcevDU7WLNkzJ3g9MeCcTXB3adpgRSrFLQCEpv7H1+/X/BQAA//+RR2W1",
	"TooAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../core/v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
