// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9a3PbNtb/V8Fy/zOx9y/R1+RpPNOZx+skrbdJ49pO9kXd6UDkkYQ1CbAAKFvN+Ls/",
	"cw4AXiTSlhPHSbZ601okrgfn8vsdgMiHKFF5oSRIa6KDD5FJppBz+vOIW56pCf5ZaFWAtgLoBS/Ee9BG",
	"KIm/UjCJFoWln9HhybF/x1IYCwmG2SmwmXsGKXMdMDVmdioM01BoMCAtxwbwMZdMjf4DiY3ZGWisyMxU",
	"lVnKEiVnoC3TkKiJFH9WrRlmFXWTcQvGMiEtaMkzNuNZCQPGZcpyPmcasF1WykYLVMTE7I3SwIQcqwM2",
	"tbYwB1tbE2Hjy+9MLNRWovK8lMLOtxIlrRaj0ipttlKYQbZlxGTIdTIVFhJbatjihRjSYCVOysR5+ncN",
	"RpU6ARNHg8jOC4gOImO1kJPoZhBdCpkuy/InIVMmDOPMlXRjrUWGj3DWpy/PzlnowInVSbAuamphoiCE",
	"HIN2Jcda5dQKyLRQQlr6kWQCpGWmHOXC4ir9UYKxKOeYHXEplWUjYGWRcgtpzI4lO+I5ZEfcwGcXJUrP",
	"DFFk3cLMwfKUW44C/X8axtFB9PetWsu3vM5szXZGYPnO76oAyQvx+1uS2RuwHFsxBSR3teAt5AyLYhXL",
	"bWlWreQK39wMIpSu0JBGB782bcurRWNCflS/VZN2y4x9+1aPLeTLitR42VAJtDReFJlInO1ZyAs0IKcS",
	"nCWuVsyOLSu0mokUDBo1LzOLtjgWk1K7qs6ImJ1yyxIuUTeS0liVk4ldTUEynqZBX1udKsbZOAOwuJZf",
	"xs98IYv8FN1trOhHKCxWc0r78Np3qK0Y88R2LJlkPCPHbMUMGPcF2VjpnHcsv+Q5LLfylv7gGZuWOZdD",
	"DTzlowxYKkyR8TnDWtikk3roBFuHa54XGQ78l6O3/95lL4S5ZMc5n0DXSrgHK4szTPscq90MolKLDgmE",
	"Kb87PWYbb4+OmYYxaJAJDNi709cDdrbHCm6nAwY2iTfbo/6j5HN0oBrSKbdbegrZcKSUTYZ/JOpqd3kS",
	"C4uLQ1px8c795NvDx6dkOQsrx45lkpXoHdxwBMp0OCpFloJmqrRFGcqamL1wHoRiNkYALiRoJsZMyWzO",
	"lIT2oskyx8FXJaNBFKbLcxENImEU/i15omTKh+7nLE8v8X9T1GDNr6JBNEmgMX0vo0F0PcQuhjOuUXMM",
	"9tUjkKPGEHqK/OJH1vP6kAbc8/KYBt5X00/v1kLv3aT73pIsel6ekoh6Xv6AkmsryhG3MFF67pSEFjQ6",
	"iBqOPRosxyCqQQoUYgsTFvLmMpu5wQg2aDV171ULfZ2F1jreHTY7WJhciG2jrMMKjlqRbywgS9uRD72k",
	"GAtIGbc0QZYhtmEbvAqfZpMwqZqB1iJNMTzaELtc6Zh5Rzx0lX2EHZdZhji2yHgC1Hj7/QYisxz0BNLN",
	"ZY/qgjaF1jQVzo+eNEpYXcLg1umGbkDO3nNtBqxQ2poBm6mszMEMqqBnulzYh8jXwz9fv/3h99cv3798",
	"HR1ECBbRFVFruJjPt59vH+B/aG2WXJabyBm54ftN519nb39mrqIDDhiyk8aCs4JrnoNFqIxrZKcgNM5b",
	"pCSCRtiux4NRqCtYvQDLRQYpS1VS5gF9DFhBfp+PMoTiLOf6MlVXshEJlz35bW77BYIKr8sdY6heEijH",
	"LkhzlV4wRKZ0UMKYnRBMQSWTKdoJYT/XEqIrQq/LGpaDMRhQl0Zx6gMR8yUYXBcZd+K/ms5dtBatPlD6",
	"V2hXVrFUMSGNBZ62Y+I5VcOxt+rG7J0BJidCXg+LrDTNykuR3lsTLs8tcINwBaFJYI0abQFuNCwSw9lC",
	"BK8HdGewDoK8I2C/FsbeivexgEOsGf6lxqzx0nw5zP3X4faoEmZZmK97lqMqviLwrLFqxLXm83U64StJ",
	"J+ACO252P5LlFOAOu6eG0Vyz7O04Ovj1EzIdi9m9pE77LcB/XEjv7Wzld0eQKTlxS3kmcpFxjRZLsKwg",
	"kCLZT+UItATrLKT2h5BOYMiL4m53GAa1LJbfFiP8Gy9KCnDtzEcwU/by2oJMDasFwa6EnVbTM4kqhJx0",
	"xvpGk6eBvXXFO/8quK9Ci5zreU2eCACG6NIkxoEpLftmX7XDmxz2E2tEa/EkHjCiTQN2fPaWRENcjRFX",
	"M+049Wvg3rcQ5cDBiOfeSU1Ry3xFx8/uqoalcGnv6w2r7EOHV+yk5CeLy4LUHHVBlTUit3wSs7OyIHjK",
	"WrzdEHE3FXP3uLeTuBda5WCnUJrGnw9B28986qcXBWCBVsxup++WoWAHd2gwvhUXoyKJN4NAEu+zli0a",
	"Rk20UO6KrTSxMTbi0kQ/d+aWfrwlpWSmiNCFrMSEeErISXfQaOH9dzrriv/yEn0DXHs806rS2ehU5VB0",
	"omt0zeEt6qNPgEEbnRZa9eY7RdKF+LAppRm5UzQMj39brWJN6i+IS0j27rizE59F1l1m6N5gb0U5yoSZ",
	"4o+O7jZwubmcY0kLPKfV2ewB9g33vKK61C79ZhCZqdL2RXOgS36XjbSAMVMShpmQwBqvu4bfOU7jPEu/",
	"jvgCdQSjRWnqCy3ABCyBuClkRfwAOc2Qy/RusCvszLjIyFZCGVYaHMKRkImQGJBYrlLIHCHzvMnQaENA",
	"RBAwYOZSFMbtFBhLLSZTLiVk/g3B/hxSwW3d2WLU8lUog+BaiQbRmBuLDjR0Hh1Eu/H+frwdDSJqG0vv",
	"xvt78Tb5WT6JDqLZbrz/lIrMAhuK/COMZc2OQvsL7qliwtEZJKUWds7G4hqNw7cds5MMuEHYO9E8hbjB",
	"Rf0g92gE9Yj2l0e03zGipanXLewtt4CPPibUBgzbEWlnwoiRyIS9T7R4X1daDIHUftOeGzp5R2i8PZPd",
	"8iwY9YVkSFBCsGumJhWG6rHQ+RXXOIJUixnlgpup6SlkeTTAiJ9mYOllXihD5RHe3zuViSN9exYtzelV",
	"PZCFNy/CuBae96Sv8dWPbtQLT3+pJrHUUpjTYtc0xfYCNLIJq5GVfgTwIVISfAst9eAT7LX9MBUTQO1H",
	"1V5AMpWpLCEm/8bRm4D+Ggynyc97vGttBQ+EV2gay3mpo2Pm3pEzFXleOrdZGUnM3pS25Fk2Z3CdZKVB",
	"bkAsh+DsKyIHB8xM+e7TZwdx3Mas/jHfg/T504TDaHt3PIZn3yVp+nycfre/v/3s2XfbHJ7vpc/29pLR",
	"zrP93d10exu+4/+T7O4+f/p0tP8s3b8l32a6YQyGjzqe+PSDrGPHoE7bNmmVd6IUTbqD7KUoTrnsQk9n",
	"kM9AM41v0StUsazK6ofWU6EhsdnckTo3MhfacBH+HBqrEZK4RAZF6amyY3G9SHwvyu3tPfh+J96Otxn9",
	"SHZi7+27Bt4VequU90eNd8VIixFkSBtz3TE3oilEg2gn3nHxc3X7oKi0OC2imaihOOSizLJ+NXbq3xZs",
	"HbeXup/1pTXPIOfSiqTSOZGCtGIsQAfqvBPvxnsDjNzb8fZQJzubMasy2uM6bc6UToFya8juwypMNC+m",
	"7XH2DXMh8M2qPFHltFbIgBzWw1nca2NjlWXqKljPIkxDtdA1vrqQXAOTKgVUC9ZQLJoSTTIMjGHRjI/w",
	"T7JbZXzV+EK+a1inK+nIaMpG8xoVbjjb3wxocCMvMysKeqL0haxMmG2YhsluNjage4JHc5vuQvptt9b+",
	"WeCnMXt5zclk0OkggucTQtvO1+alsa09vvhC3pEket8CQ+2Vqt/RVrhWGWJgRTZsAJwWGeikEQGXpJqP",
	"MUgH2pTeH2TUw3jhG+t8eVL3UE/x1h2I3t2H9c7DV7PzcO9dh/WOw19tx+HW/KLPLeKbUWd2sRmE4krr",
	"KApU1MmlBDKVYKAf5lzyCaR3bFU+Uirv4zJjj5YUu0c+7EHTWV82k/UQGYZeba+O8XbrO71unqMlqZRa",
	"k8Nxb1vAy0218ziOw/BdnTXag8U1rxtcyW8v+omj0O+yJ1/cdqtH2OUe+iTlRUSeX4MttT84RGuLJu6p",
	"SqrkExtKKEvaTY2v4cEjwINEpV1kuJwg0oWU/Xh+fhIWB8vWp2qdkg/YNhNjhqHUuOPbbsORznPZvcaB",
	"VBTNBPQaKDw4UOg5bXW4dDp62Y/XnsrJsQDdv/WkgZvugJHzZCok9HZVHe6qOsCFFpLGcBG94iIrNVxE",
	"4UgZO/YDciogDIO8sNgGMlNhmFStY2w8bEHE7JCd0jBZknGN7Iw+cSA19pMlNR6V6HnAkOY2uGB3RLvd",
	"xXlZ1sJjb4k2HrCL6KxMEjDmIsIY15jpZ1cbJKdDLtNhfUrv9jRDFz70E/duotKAwa0n0/ojzUefVama",
	"+Cc30HFcZZU9rd423Q5X127DCmmWqpUAYw1L6bynA7N0kh2XwlbhezmmC8MOT47ZKYSQfpsQSQJLmohP",
	"WRWo0YGWpBmNVE99/oZ6a6qLSwYKO2W0PPQ9TpqiI3YZjoShGBjIsuNMQMaNPddcGidMkfdsTWM5ZkUO",
	"gR34sdqqLqTOPaPQvK3iSCSBglZoQT88xLbu5RCJDrDKR4VDqP5sK8ooLB0fqdL6EVfD63QNamQw0KQ/",
	"gPTW3z37OFCteFKVdPinLY0rbjCQshE3kLKycN02Y+qz/c6Y2u+cNwjObzJXoj4VEPp8Ylaa6WoftvXq",
	"bc+nbpWH6VCjT/U3Zyu57UoOg5DtO9cI3V7xzMCAvZOXUl3JZrIN30eDiApEg8iXWDXj1h6db2vhaWh6",
	"4XHV022zvmOzs9I00QQxjdkdFkhGAd3/+cmb90BBFH81XrwA6Z69opPty0Up6Am3Ad36EZzcCdeGip7N",
	"ZUJ/vOeZwP+foscq7bE80WqiwaByvEPk5UR6VkASir7xqeG3VxK0oXHNRAIvAKOnMBjLsNJqC/NSapVl",
	"SEFPHfxrzHfpXXu6R+gNx3RA/kxMsM/lJnrLVLLsLVEJubdEezinUCgjrNLzTtGjxHtfLK1P82W1Vq8y",
	"ABtWgX50rZpbjcbauQfNFXRPVl3HDrWv0l2dGU461FmnpYIPdo7XzKWdghVJIxFBqf0pn8GACdpOwKiQ",
	"CWPddyAzroUqTQWbPU9lhzUfQb6BDdRfsqkx+1CfMR2wMLCbzmSAFbLssN83fE5bDmCRbqHfKg1o+s1Z",
	"JnJh3YYLMFnmI5choryAJ2+QOjJaf8hRBR8KYJpNuWE5YlKSUANRY/iqcLgq+B8lVLx2RONIMU4LY+iF",
	"o/CeQgV63GBbKHkKmQ750J6AVThMLWDm0IGEa+KTxMqr40WVuI+cmGiLDT2aEcYipqK2cFiesBXK6XgQ",
	"mZ9pOzOJ806mXE4gRYxOIrBTLhlnY7hiuZAliovWtODGIAE8p+8/3IqHpAPtLlXSdnur7hwUzTMsrRfl",
	"lcgyHKLbZkx4FiTlJe3Wciy0oTxZoSQGo1JmYAybq9KNR0MCohKlVZcg/YfbkoHWOB0XOHv4XO4+vnE7",
	"ZWXXpy/nLY0y5cjgwkrrlcuPkwR/NRXJlLnNQuvNB1JXJCx0mIpneBCeOmUJmeDU7SHicjipGsggQQI0",
	"wEqLel7NIwzKsNJFyvDxlm8mCD2DsWWlJOORKVO5sBZSlpaUdjCgBc/En57LNQdK65gXGVhgGyBI00eQ",
	"8NIgd3TE1LJkWspLbEnVb8OnTTYgYSq0Wc9Hgxed08DFObmJCPMpMwkpEUWf5JKOz3binacsVSGB0+jD",
	"aTkiTInLiJOovnxa1Buc2T/AWJGTq/+HszbxJ/gcqMpw/WgQR5RqqTJr2K8G8pR9bVsVPJ/S/gdc+y+D",
	"7wTGNysAxsaXEMtHbOqPA8RiAOFZxgq0fsqUdQYRZxMi7ExjDe/FyH/7sokGbjtyw5R54lVyuPsDx45D",
	"Fks7CL6wYxbzyheKBDq/bqDxeBRuLM+Lbr9QkTmffkPu4qaSrs7WUsjgY/ryBkDV79Pf5Baidsicd0sq",
	"79JKPjb4cIPEeaNIwdBBEOL1MTtRRZnRF4xB3vQZcsxOgad0mGZFXudOU3zC8r/hBblul1O9hHmAMku3",
	"dYRIrvSESzReOtrhTkHizw2TqMI9dQ55s5mpX9Ki7qsbKKA0PqO85foNhXCwa5UayV9umbqSJqT03XME",
	"b+yCklhb2NdF1P9VLYbBViDvvLPCwx4vROq2OiBkGtjiiWlsATTO39xyzcgqHuqE22TqsT6Or9rx6daJ",
	"MVHXBWeieiyrTslahe4MJdXkgzyl6xPc+Rz6K1czMi3wB4uXNjO5nXYtG312faJIQPSdTPeuHipm91Ad",
	"NvLZKaXDoaF4KaugisgPoythsLTbZfzhbPok3ElrBFyDPizdTNyvV8Fa//Xv82jgbsnChtzbei5TawvS",
	"Xz05Trtn8u7d8YvKApy5NVJCXqNrjBmzN7zw2bBW+TokxajotBso6Wsj0PMo2CCO5HfiW2HqhfgJcO43",
	"A/fZvece/soWjMFZdBBZ4Pn/jjMxmdrEZrFQdYs4iVf0htC4Vhk7B57TV12Zl4E52Npq1V7yTb+2m/ht",
	"o6vapt8UcgHLbahDknHtvnRz5wToM2w1drcIUW4H0gl6ZazT/Ij/SunLTPHUxBfyQp6H5Gsw1o3ZDs+K",
	"Kd/ZrBO69GBoLJ9AI8o7CKABQTGFJKs8j3DHwTKRgHS5Wi+zw4InU2C7dOavLaarq6uY0+tY6cmWr2u2",
	"Xh8fvfz57OVwN96OpzbPSH2FpeODC+I/PDluneoPEyFNdH4kOoj24u14xxsHKfqW30+mHxOwPUeF/L43",
	"a+0mVq4D1ZzKhYMd1EO4QoHS/R0u1Z9crQqiBElxAwQ2dEVMtWXnXGyTkHoLohawAUJTOTrLBpfyhZ4E",
	"BvbEY2jPXQoNMyL1bYLSY0kVQ/f2zzsi8M2gC1g4BuOoLpZMbM0riMR44hjwocMNQvvzlO07c2AGem6n",
	"/vPUroFSrTPf6yOO1h2yHIRDHkSDSE2URhFfAnvy/ZMBe/I9/hfN8snfvn8SjtheRJcw3/me1m1ncAnz",
	"3b+5H7sX0WbfTKnHj5spalLOr0Ve5i0+6RSvmmST5dYM9rzOKBAadfSpX9Fa1ZkYt7UcroWxrtGFVEHO",
	"544ltq+VMQ3DERIdZE3OSUK9miFyYVtyunPL/oY+nXIjJ0exu70dYoa/MaNxV8/Wf/xORN3DCodz6Awp",
	"RaQFBvYTerD9B+yw2opY6uufPGUBZlGnO4/Q6TvJSzsliJ26XvceoddXSo/o1iHqcvf5I3R5rhR7w+U8",
	"iNhg108fZbZnHjy8k1U60SFvPjGtqwXo/qHOw8xEbBlfioTLgdAVDQdlHTIFY/+p0vlDG42baw19rS7h",
	"ZslWdz5Pt10CStfG+tmNdfsxjPVIyXEmHGFau4eGe7geBstHOBjw7s2gRtJbH/xfN1sVUb8TWdP55nDr",
	"6lF9vLYXY1OFu3D2Yraly3kRRiCyXKPclu+qXcv9YOQnYPyvDn0/PMr+FOz5bSG76o6yNbr7QgFj/xG6",
	"/FlZ9kqVMl1HjI8ClHQ9FRG5Xu/fApbH7lbTr8X9//ZZca675K5DA+pJta73omRctav26Pi4b7hrjPxf",
	"7PIeHZZ/I9jYg+DbEPLWB/Q8N85JZmA7b9GlUxdtd3kXXHaVvk6HOVix75Zf6+mf/ndvb/2ZUF+/KgWw",
	"t3ZCn8sJfX0uoZP4/kDHFu9jyT+AXZvxo5rxHVBmbct/PVsuStt1ya37dwjuQ2R8nbVFfwM0qjpkczeP",
	"emTnsyZuaz+7Jm6PTNzuTdRu2Sht0bNPjQD0L4RQg2uStDb4dXL6wfjZLQZcs7KHsN6Ju0DkGyFGa9td",
	"2+6X5mPcJh0n7elrgZXsl0o+oAXTgL4IFRpS1///fqtw62cWK52selSvsuYda96xPsf1WZNZdFnBauSl",
	"ncN6CO/p7hf7NjJJX517XJ9yXTvktUP+bz9YS9mnrfoqql722ryC9T489izcR/U5diPWNHbtatY09n40",
	"9n6G3CS0X6Epr9nsms2uPdpfm1vez6G1WeY37NK+fYa59h5r6vXXol50NQ7dGUdexl1ZssULsTXbobuw",
	"fVtLl6YFF0b/Cljn1SEL57Nufrv5vwAAAP//f9s6roWSAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
