// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v1beta1

import v1beta1 "github.com/flightctl/flightctl/api/core/v1beta1"

type AuthConverterImpl struct{}

func (c *AuthConverterImpl) TokenRequestToDomain(source *v1beta1.TokenRequest) *v1beta1.TokenRequest {
	return source
}
func (c *AuthConverterImpl) TokenResponseFromDomain(source *v1beta1.TokenResponse) *v1beta1.TokenResponse {
	return source
}
