// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v1beta1

import (
	v1beta1 "github.com/flightctl/flightctl/api/core/v1beta1"
	domain "github.com/flightctl/flightctl/internal/domain"
)

type CertificateSigningRequestConverterImpl struct{}

func (c *CertificateSigningRequestConverterImpl) FromDomain(source *v1beta1.CertificateSigningRequest) *v1beta1.CertificateSigningRequest {
	return source
}
func (c *CertificateSigningRequestConverterImpl) ListFromDomain(source *domain.ResourceList[v1beta1.CertificateSigningRequest]) *v1beta1.CertificateSigningRequestList {
	var pV1beta1CertificateSigningRequestList *v1beta1.CertificateSigningRequestList
	if source != nil {
		var v1beta1CertificateSigningRequestList v1beta1.CertificateSigningRequestList
		v1beta1CertificateSigningRequestList.ApiVersion = APIVersion()
		v1beta1CertificateSigningRequestList.Items = (*source).Items
		v1beta1CertificateSigningRequestList.Kind = CertificateSigningRequestListKind()
		v1beta1CertificateSigningRequestList.Metadata = c.domainPaginationToV1beta1ListMeta((*source).Pagination)
		pV1beta1CertificateSigningRequestList = &v1beta1CertificateSigningRequestList
	}
	return pV1beta1CertificateSigningRequestList
}
func (c *CertificateSigningRequestConverterImpl) ListParamsToDomain(source v1beta1.ListCertificateSigningRequestsParams) v1beta1.ListCertificateSigningRequestsParams {
	return source
}
func (c *CertificateSigningRequestConverterImpl) ToDomain(source v1beta1.CertificateSigningRequest) v1beta1.CertificateSigningRequest {
	return source
}
func (c *CertificateSigningRequestConverterImpl) domainPaginationToV1beta1ListMeta(source domain.Pagination) v1beta1.ListMeta {
	var v1beta1ListMeta v1beta1.ListMeta
	v1beta1ListMeta.Continue = source.Continue
	v1beta1ListMeta.RemainingItemCount = source.RemainingItemCount
	return v1beta1ListMeta
}
