// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v1beta1

import v1beta1 "github.com/flightctl/flightctl/api/core/v1beta1"

type CommonConverterImpl struct{}

func (c *CommonConverterImpl) LabelListFromDomain(source *[]string) *[]string {
	return source
}
func (c *CommonConverterImpl) ListLabelsParamsToDomain(source v1beta1.ListLabelsParams) v1beta1.ListLabelsParams {
	return source
}
func (c *CommonConverterImpl) PatchRequestToDomain(source []struct {
	Op    v1beta1.PatchRequestOp `json:"op"`
	Path  string                 `json:"path"`
	Value interface{}            `json:"value,omitempty"`
}) []struct {
	Op    v1beta1.PatchRequestOp `json:"op"`
	Path  string                 `json:"path"`
	Value interface{}            `json:"value,omitempty"`
} {
	return source
}
func (c *CommonConverterImpl) StatusFromDomain(source v1beta1.Status) v1beta1.Status {
	return source
}
