// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v1beta1

import (
	v1beta1 "github.com/flightctl/flightctl/api/core/v1beta1"
	domain "github.com/flightctl/flightctl/internal/domain"
)

type DeviceConverterImpl struct{}

func (c *DeviceConverterImpl) DecommissionToDomain(source v1beta1.DeviceDecommission) v1beta1.DeviceDecommission {
	return source
}
func (c *DeviceConverterImpl) FromDomain(source *v1beta1.Device) *v1beta1.Device {
	return source
}
func (c *DeviceConverterImpl) GetRenderedParamsToDomain(source v1beta1.GetRenderedDeviceParams) v1beta1.GetRenderedDeviceParams {
	return source
}
func (c *DeviceConverterImpl) LastSeenFromDomain(source *v1beta1.DeviceLastSeen) *v1beta1.DeviceLastSeen {
	return source
}
func (c *DeviceConverterImpl) ListFromDomain(source *domain.DeviceList) *v1beta1.DeviceList {
	var pV1beta1DeviceList *v1beta1.DeviceList
	if source != nil {
		var v1beta1DeviceList v1beta1.DeviceList
		v1beta1DeviceList.ApiVersion = APIVersion()
		v1beta1DeviceList.Items = (*source).ResourceList.Items
		v1beta1DeviceList.Kind = DeviceListKind()
		v1beta1DeviceList.Metadata = c.domainPaginationToV1beta1ListMeta((*source).ResourceList.Pagination)
		v1beta1DeviceList.Summary = (*source).Summary
		pV1beta1DeviceList = &v1beta1DeviceList
	}
	return pV1beta1DeviceList
}
func (c *DeviceConverterImpl) ListParamsToDomain(source v1beta1.ListDevicesParams) v1beta1.ListDevicesParams {
	return source
}
func (c *DeviceConverterImpl) ResumeRequestToDomain(source v1beta1.DeviceResumeRequest) v1beta1.DeviceResumeRequest {
	return source
}
func (c *DeviceConverterImpl) ResumeResponseFromDomain(source v1beta1.DeviceResumeResponse) v1beta1.DeviceResumeResponse {
	return source
}
func (c *DeviceConverterImpl) ToDomain(source v1beta1.Device) v1beta1.Device {
	return source
}
func (c *DeviceConverterImpl) domainPaginationToV1beta1ListMeta(source domain.Pagination) v1beta1.ListMeta {
	var v1beta1ListMeta v1beta1.ListMeta
	v1beta1ListMeta.Continue = source.Continue
	v1beta1ListMeta.RemainingItemCount = source.RemainingItemCount
	return v1beta1ListMeta
}
