// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v1beta1

import (
	v1beta1 "github.com/flightctl/flightctl/api/core/v1beta1"
	domain "github.com/flightctl/flightctl/internal/domain"
)

type EnrollmentRequestConverterImpl struct{}

func (c *EnrollmentRequestConverterImpl) ApprovalStatusFromDomain(source *v1beta1.EnrollmentRequestApprovalStatus) *v1beta1.EnrollmentRequestApprovalStatus {
	return source
}
func (c *EnrollmentRequestConverterImpl) ApprovalToDomain(source v1beta1.EnrollmentRequestApproval) v1beta1.EnrollmentRequestApproval {
	return source
}
func (c *EnrollmentRequestConverterImpl) ConfigFromDomain(source *v1beta1.EnrollmentConfig) *v1beta1.EnrollmentConfig {
	return source
}
func (c *EnrollmentRequestConverterImpl) FromDomain(source *v1beta1.EnrollmentRequest) *v1beta1.EnrollmentRequest {
	return source
}
func (c *EnrollmentRequestConverterImpl) GetConfigParamsToDomain(source v1beta1.GetEnrollmentConfigParams) v1beta1.GetEnrollmentConfigParams {
	return source
}
func (c *EnrollmentRequestConverterImpl) ListFromDomain(source *domain.ResourceList[v1beta1.EnrollmentRequest]) *v1beta1.EnrollmentRequestList {
	var pV1beta1EnrollmentRequestList *v1beta1.EnrollmentRequestList
	if source != nil {
		var v1beta1EnrollmentRequestList v1beta1.EnrollmentRequestList
		v1beta1EnrollmentRequestList.ApiVersion = APIVersion()
		v1beta1EnrollmentRequestList.Items = (*source).Items
		v1beta1EnrollmentRequestList.Kind = EnrollmentRequestListKind()
		v1beta1EnrollmentRequestList.Metadata = c.domainPaginationToV1beta1ListMeta((*source).Pagination)
		pV1beta1EnrollmentRequestList = &v1beta1EnrollmentRequestList
	}
	return pV1beta1EnrollmentRequestList
}
func (c *EnrollmentRequestConverterImpl) ListParamsToDomain(source v1beta1.ListEnrollmentRequestsParams) domain.ResourceListParams {
	var domainResourceListParams domain.ResourceListParams
	domainResourceListParams.Continue = source.Continue
	domainResourceListParams.LabelSelector = source.LabelSelector
	domainResourceListParams.FieldSelector = source.FieldSelector
	domainResourceListParams.Limit = source.Limit
	return domainResourceListParams
}
func (c *EnrollmentRequestConverterImpl) ToDomain(source v1beta1.EnrollmentRequest) v1beta1.EnrollmentRequest {
	return source
}
func (c *EnrollmentRequestConverterImpl) domainPaginationToV1beta1ListMeta(source domain.Pagination) v1beta1.ListMeta {
	var v1beta1ListMeta v1beta1.ListMeta
	v1beta1ListMeta.Continue = source.Continue
	v1beta1ListMeta.RemainingItemCount = source.RemainingItemCount
	return v1beta1ListMeta
}
