// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v1beta1

import (
	v1beta1 "github.com/flightctl/flightctl/api/core/v1beta1"
	domain "github.com/flightctl/flightctl/internal/domain"
)

type EventConverterImpl struct{}

func (c *EventConverterImpl) ListFromDomain(source *domain.ResourceList[v1beta1.Event]) *v1beta1.EventList {
	var pV1beta1EventList *v1beta1.EventList
	if source != nil {
		var v1beta1EventList v1beta1.EventList
		v1beta1EventList.ApiVersion = APIVersion()
		v1beta1EventList.Items = (*source).Items
		v1beta1EventList.Kind = EventListKind()
		v1beta1EventList.Metadata = c.domainPaginationToV1beta1ListMeta((*source).Pagination)
		pV1beta1EventList = &v1beta1EventList
	}
	return pV1beta1EventList
}
func (c *EventConverterImpl) ListParamsToDomain(source v1beta1.ListEventsParams) domain.ResourceListParams {
	var domainResourceListParams domain.ResourceListParams
	domainResourceListParams.Continue = source.Continue
	domainResourceListParams.FieldSelector = source.FieldSelector
	domainResourceListParams.Limit = source.Limit
	return domainResourceListParams
}
func (c *EventConverterImpl) domainPaginationToV1beta1ListMeta(source domain.Pagination) v1beta1.ListMeta {
	var v1beta1ListMeta v1beta1.ListMeta
	v1beta1ListMeta.Continue = source.Continue
	v1beta1ListMeta.RemainingItemCount = source.RemainingItemCount
	return v1beta1ListMeta
}
