// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v1beta1

import (
	v1beta1 "github.com/flightctl/flightctl/api/core/v1beta1"
	domain "github.com/flightctl/flightctl/internal/domain"
)

type FleetConverterImpl struct{}

func (c *FleetConverterImpl) FromDomain(source *v1beta1.Fleet) *v1beta1.Fleet {
	return source
}
func (c *FleetConverterImpl) GetParamsToDomain(source v1beta1.GetFleetParams) v1beta1.GetFleetParams {
	return source
}
func (c *FleetConverterImpl) ListFromDomain(source *domain.ResourceList[v1beta1.Fleet]) *v1beta1.FleetList {
	var pV1beta1FleetList *v1beta1.FleetList
	if source != nil {
		var v1beta1FleetList v1beta1.FleetList
		v1beta1FleetList.ApiVersion = APIVersion()
		v1beta1FleetList.Items = (*source).Items
		v1beta1FleetList.Kind = FleetListKind()
		v1beta1FleetList.Metadata = c.domainPaginationToV1beta1ListMeta((*source).Pagination)
		pV1beta1FleetList = &v1beta1FleetList
	}
	return pV1beta1FleetList
}
func (c *FleetConverterImpl) ListParamsToDomain(source v1beta1.ListFleetsParams) v1beta1.ListFleetsParams {
	return source
}
func (c *FleetConverterImpl) ToDomain(source v1beta1.Fleet) v1beta1.Fleet {
	return source
}
func (c *FleetConverterImpl) domainPaginationToV1beta1ListMeta(source domain.Pagination) v1beta1.ListMeta {
	var v1beta1ListMeta v1beta1.ListMeta
	v1beta1ListMeta.Continue = source.Continue
	v1beta1ListMeta.RemainingItemCount = source.RemainingItemCount
	return v1beta1ListMeta
}
