// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v1beta1

import (
	v1beta1 "github.com/flightctl/flightctl/api/core/v1beta1"
	domain "github.com/flightctl/flightctl/internal/domain"
)

type OrganizationConverterImpl struct{}

func (c *OrganizationConverterImpl) ListFromDomain(source *domain.ResourceList[v1beta1.Organization]) *v1beta1.OrganizationList {
	var pV1beta1OrganizationList *v1beta1.OrganizationList
	if source != nil {
		var v1beta1OrganizationList v1beta1.OrganizationList
		v1beta1OrganizationList.ApiVersion = APIVersion()
		v1beta1OrganizationList.Items = (*source).Items
		v1beta1OrganizationList.Kind = OrganizationListKind()
		v1beta1OrganizationList.Metadata = c.domainPaginationToV1beta1ListMeta((*source).Pagination)
		pV1beta1OrganizationList = &v1beta1OrganizationList
	}
	return pV1beta1OrganizationList
}
func (c *OrganizationConverterImpl) ListParamsToDomain(source v1beta1.ListOrganizationsParams) domain.ResourceListParams {
	var domainResourceListParams domain.ResourceListParams
	domainResourceListParams.FieldSelector = source.FieldSelector
	return domainResourceListParams
}
func (c *OrganizationConverterImpl) domainPaginationToV1beta1ListMeta(source domain.Pagination) v1beta1.ListMeta {
	var v1beta1ListMeta v1beta1.ListMeta
	v1beta1ListMeta.Continue = source.Continue
	v1beta1ListMeta.RemainingItemCount = source.RemainingItemCount
	return v1beta1ListMeta
}
