// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v1beta1

import (
	v1beta1 "github.com/flightctl/flightctl/api/core/v1beta1"
	domain "github.com/flightctl/flightctl/internal/domain"
)

type RepositoryConverterImpl struct{}

func (c *RepositoryConverterImpl) FromDomain(source *v1beta1.Repository) *v1beta1.Repository {
	return source
}
func (c *RepositoryConverterImpl) ListFromDomain(source *domain.ResourceList[v1beta1.Repository]) *v1beta1.RepositoryList {
	var pV1beta1RepositoryList *v1beta1.RepositoryList
	if source != nil {
		var v1beta1RepositoryList v1beta1.RepositoryList
		v1beta1RepositoryList.ApiVersion = APIVersion()
		v1beta1RepositoryList.Items = (*source).Items
		v1beta1RepositoryList.Kind = RepositoryListKind()
		v1beta1RepositoryList.Metadata = c.domainPaginationToV1beta1ListMeta((*source).Pagination)
		pV1beta1RepositoryList = &v1beta1RepositoryList
	}
	return pV1beta1RepositoryList
}
func (c *RepositoryConverterImpl) ListParamsToDomain(source v1beta1.ListRepositoriesParams) v1beta1.ListRepositoriesParams {
	return source
}
func (c *RepositoryConverterImpl) ToDomain(source v1beta1.Repository) v1beta1.Repository {
	return source
}
func (c *RepositoryConverterImpl) domainPaginationToV1beta1ListMeta(source domain.Pagination) v1beta1.ListMeta {
	var v1beta1ListMeta v1beta1.ListMeta
	v1beta1ListMeta.Continue = source.Continue
	v1beta1ListMeta.RemainingItemCount = source.RemainingItemCount
	return v1beta1ListMeta
}
