// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v1beta1

import (
	v1beta1 "github.com/flightctl/flightctl/api/core/v1beta1"
	domain "github.com/flightctl/flightctl/internal/domain"
)

type ResourceSyncConverterImpl struct{}

func (c *ResourceSyncConverterImpl) FromDomain(source *v1beta1.ResourceSync) *v1beta1.ResourceSync {
	return source
}
func (c *ResourceSyncConverterImpl) ListFromDomain(source *domain.ResourceList[v1beta1.ResourceSync]) *v1beta1.ResourceSyncList {
	var pV1beta1ResourceSyncList *v1beta1.ResourceSyncList
	if source != nil {
		var v1beta1ResourceSyncList v1beta1.ResourceSyncList
		v1beta1ResourceSyncList.ApiVersion = APIVersion()
		v1beta1ResourceSyncList.Items = (*source).Items
		v1beta1ResourceSyncList.Kind = ResourceSyncListKind()
		v1beta1ResourceSyncList.Metadata = c.domainPaginationToV1beta1ListMeta((*source).Pagination)
		pV1beta1ResourceSyncList = &v1beta1ResourceSyncList
	}
	return pV1beta1ResourceSyncList
}
func (c *ResourceSyncConverterImpl) ListParamsToDomain(source v1beta1.ListResourceSyncsParams) v1beta1.ListResourceSyncsParams {
	return source
}
func (c *ResourceSyncConverterImpl) ToDomain(source v1beta1.ResourceSync) v1beta1.ResourceSync {
	return source
}
func (c *ResourceSyncConverterImpl) domainPaginationToV1beta1ListMeta(source domain.Pagination) v1beta1.ListMeta {
	var v1beta1ListMeta v1beta1.ListMeta
	v1beta1ListMeta.Continue = source.Continue
	v1beta1ListMeta.RemainingItemCount = source.RemainingItemCount
	return v1beta1ListMeta
}
