// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package v1beta1

import (
	v1beta1 "github.com/flightctl/flightctl/api/core/v1beta1"
	domain "github.com/flightctl/flightctl/internal/domain"
)

type TemplateVersionConverterImpl struct{}

func (c *TemplateVersionConverterImpl) FromDomain(source *v1beta1.TemplateVersion) *v1beta1.TemplateVersion {
	return source
}
func (c *TemplateVersionConverterImpl) ListFromDomain(source *domain.ResourceList[v1beta1.TemplateVersion]) *v1beta1.TemplateVersionList {
	var pV1beta1TemplateVersionList *v1beta1.TemplateVersionList
	if source != nil {
		var v1beta1TemplateVersionList v1beta1.TemplateVersionList
		v1beta1TemplateVersionList.ApiVersion = APIVersion()
		v1beta1TemplateVersionList.Items = (*source).Items
		v1beta1TemplateVersionList.Kind = TemplateVersionListKind()
		v1beta1TemplateVersionList.Metadata = c.domainPaginationToV1beta1ListMeta((*source).Pagination)
		pV1beta1TemplateVersionList = &v1beta1TemplateVersionList
	}
	return pV1beta1TemplateVersionList
}
func (c *TemplateVersionConverterImpl) ListParamsToDomain(source v1beta1.ListTemplateVersionsParams) domain.ResourceListParams {
	var domainResourceListParams domain.ResourceListParams
	domainResourceListParams.Continue = source.Continue
	domainResourceListParams.LabelSelector = source.LabelSelector
	domainResourceListParams.FieldSelector = source.FieldSelector
	domainResourceListParams.Limit = source.Limit
	return domainResourceListParams
}
func (c *TemplateVersionConverterImpl) domainPaginationToV1beta1ListMeta(source domain.Pagination) v1beta1.ListMeta {
	var v1beta1ListMeta v1beta1.ListMeta
	v1beta1ListMeta.Continue = source.Continue
	v1beta1ListMeta.RemainingItemCount = source.RemainingItemCount
	return v1beta1ListMeta
}
